### ISSUE TITLE
Power(0(log n))

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#122]
### Take as input X and N , two numbers. Write a function to calculate X raise to power N . Target Complexity is 0(log n)....

Before making PR check this...

### Please add your image in image folder nd update readme.md file this is for all contributors 
do this then only i will be able to merge PR..
Check this
#90 (comment)

### file format :-  Power(0(log n))/CPP/power.c++

**Comment by nish7898** [comment]
https://github.com/zahinekbal/codeWith-hacktoberfest/pull/123

**Comment by SayedAlesawy** [comment]
@zahinekbal PR here: https://github.com/zahinekbal/codeWith-hacktoberfest/pull/142
