### ISSUE TITLE
Counting Divisors (using Sieve)

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#130]
We have to compute numbers of divisors of N..

### Please add your image in image folder nd update readme.md file this is for all contributorsdo this then only i will be able to merge PR..Check this
#90 (comment)

### File format:-  CountingDivisors/CPP/CountingDivisors.c++

**Comment by deepampriyadarshi** [comment]
@zahinekbal can you please review my PR #166

**Comment by zahinekbal** [comment]
> @zahinekbal can you please review my PR #166

done
