### ISSUE TITLE
Invertion Count Problem in c++

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#158]
### FILE-format:- InvertionCount/CPP/InvertionCount.c++

**Comment by Vishi13** [comment]
Can you assign this problem to me?

**Comment by Vishi13** [comment]
This problem is already done and also merged.

**Comment by zahinekbal** [comment]
Yeah I know before closing this issues I want to assigned you so that I assigned yiu
