### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jay206-Programmer** [zahinekbal/codeWith-hacktoberfest#17]
I am getting this error at __Hectoberfest Portal__. 

`Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.`

**Comment by MonarchChakri** [comment]
![image](https://user-images.githubusercontent.com/23417550/94995621-0d98af00-05bd-11eb-9f29-e14f1237dd7c.png)

**Comment by MonarchChakri** [comment]
Looks like you need to add the topic hacktoberfest for this repo

**Comment by MonarchChakri** [comment]
@zahinekbal

**Comment by zahinekbal** [comment]
I added check my repo

**Comment by Jay206-Programmer** [comment]
Its a **typing error**. You have wrote **hackoctoberfest** instead of **hacktoberfest**. 😅

**Comment by zahinekbal** [comment]
> Its a **typing error**. You have wrote **hackoctoberfest** instead of **hacktoberfest**. 😅

Sorry I did it now...
Thankyou so much 😁

**Comment by MonarchChakri** [comment]
Please update it or create a new topic to this repo. 😅

**Comment by zahinekbal** [comment]
Yeah sure
