### ISSUE TITLE
Trie question:Maximum xor pair

### ISSUE THREAD

**Issue by vaishnavijha** [zahinekbal/codeWith-hacktoberfest#25]
Given an array of integers, we have to find two elements whose XOR is maximum.

**Comment by vaishnavijha** [comment]
may i go ahead and solve this problem

**Comment by zahinekbal** [comment]
> may i go ahead and solve this problem

Sure @vaishnavijha I assigned you

**Comment by vaishnavijha** [comment]
I have added a pull request for the same. Please look if it can be merged .Thanks in advance!!
