### ISSUE TITLE
Pyramid Pattern problem

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#30]
Please before making PR make sure to follow the rule here....

i.e :- PyramidPatternProblem/CPP/PyramidPatternProblem.c++
       PyramidPatternProblem/C/PyramidPatternProblem.c
       PyramidPatternProblem/python/PyramidPatternProblem.py
      PyramidPatternProblem/java/PyramidPatternProblem.java

**Comment by vaishnavijha** [comment]
Can u assign me this?
