### ISSUE TITLE
Spiral-Print-Array

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#4]
Before making PR make sure you are using this same format i.e:-

# SpiralPrintArray/CPP/SpiralPrintArray.extention

**Comment by paritoshkray** [comment]
Can I take up this issue?

**Comment by zahinekbal** [comment]
> Can I take up this issue?

Yeah i assigned you

**Comment by paritoshkray** [comment]
We cant use / in file name. Can the file name be SpiralPrintArray.cpp?

**Comment by zahinekbal** [comment]
use the format 
SpiralPrintArray/CPP/SpiralPrintArray.extention

Make SpiralPrintArray Folder inside Add CPP folder then add file  SpiralPrintArray.extention

**Comment by paritoshkray** [comment]
Done. Please Review[https://github.com/zahinekbal/codeWith-hacktoberfest/pull/52](url)

**Comment by zahinekbal** [comment]
Nice work 👌
