### ISSUE TITLE
DepthFirstSearch(DFS)

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#59]
# DFS/CPP/DFS.C++

**Comment by promaroy** [comment]
Can I work on this??

**Comment by promaroy** [comment]
Please tell me folder format to be used

**Comment by promaroy** [comment]
I have made a PR. Please Review. [https://github.com/zahinekbal/codeWith-hacktoberfest/pull/66](url)
