### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#7]
Kindly put it like  i.e...
# SortingAlgorithm/C++/YourAlgorithm.extension..
Same for java ,c,py...
nd then make your PR

**Comment by Mayankjha997** [comment]
I want to add bubble sort in c language

**Comment by paritoshkray** [comment]
Can I add merge sort in C++?

**Comment by NidhiNivedita6** [comment]
Please assign me this. I will do selection sort in C

**Comment by zahinekbal** [comment]
> Please assign me this. I will do selection sort in C

> I want to add bubble sort in c language

yes @Mayankjha997 go ahead..

**Comment by zahinekbal** [comment]
> Can I add merge sort in C++?

Yeah go ahead @NidhiNivedita6

**Comment by sachin-611** [comment]
can i do bucket sort in c++ and selection sort ,merge sort ,shell sort python?

**Comment by zahinekbal** [comment]
> Please assign me this. I will do selection sort in C

go ahead @NidhiNivedita6

**Comment by zahinekbal** [comment]
> Can I add merge sort in C++?

go ahead @paritoshkray

**Comment by zahinekbal** [comment]
> can i do bucket sort in c++ and selection sort ,merge sort ,shell sort python?

Sure go ahead @sachin-611

**Comment by JatinArora23** [comment]
hey! 
Can i do bubble sort using python?

**Comment by zahinekbal** [comment]
> hey!
> Can i do bubble sort using python?

Sure go ahead

**Comment by ahmedashfaq027** [comment]
Hey, Can i add quick sort using Java?

**Comment by junyongxlee** [comment]
Can I do bubble sort, selection sort and insertion sort and in Java?

**Comment by theAkashDas** [comment]
Hello ...Can I add insertion sort in C??

**Comment by Ace117MC** [comment]
Can I add heap sort in C++ ?

**Comment by saiharsha-22** [comment]
@zahinekbal can I do quick sort in java?

**Comment by zahinekbal** [comment]
> Hey, Can i add quick sort using Java?

Sure @ahmedashfaq027

**Comment by zahinekbal** [comment]
> @zahinekbal can I do quick sort in java?

@saiharsha-22  I think ahmed is doing the same thing...

**Comment by sachin-611** [comment]
@zahinekbal check PR uploaded algorithms

**Comment by sachin-611** [comment]
@zahinekbal kindly change hackoctoberfest to hactoberfest in main repro its typo error by you!!

**Comment by ahmedashfaq027** [comment]
> Hey, Can i add quick sort using Java?

#32 Added QuickSort.java

**Comment by Mayankjha997** [comment]
@zahinekbal check PR uploaded algorithms

**Comment by saiharsha-22** [comment]
@zahinekbal can I add shell sort in CPP?

**Comment by Darshan-Paradox** [comment]
@zahinekbal can I add merge sort implementation in c??

**Comment by Darshan-Paradox** [comment]
@zahinekbal can I add boggo sort implementation in c??

**Comment by paritoshkray** [comment]
Can I implement radix sort in C++?

**Comment by satcasm** [comment]
@zahinekbal just added counting sort in c++.
Please review

**Comment by theAkashDas** [comment]
Please check my PR on insertion sort @zahinekbal

**Comment by ahmedashfaq027** [comment]
Hi @zahinekbal ,
I Updated my PR, Please do check! #63

**Comment by Mayankjha997** [comment]
please Review my PR #69

**Comment by Darshan-Paradox** [comment]
Please check my pull request on mergesort.c and boggosort.c @zahinekbal 
 #70

**Comment by Darshan-Paradox** [comment]
#70

**Comment by satcasm** [comment]
> @zahinekbal just added counting sort in c++.
> Please review

Hey @zahinekbal just added the correct formatting. Please review.

**Comment by carrisunrio** [comment]
Hey @zahinekbal Can i make a PR for insertion sort in C++?

**Comment by nightrainlily** [comment]
Can I add a heap sort in java?

**Comment by manvika-10** [comment]
Hi, I want to add the code of some sorting algorithm in c++ so please assign this issue to me.
