### ISSUE TITLE
BinarySearch-Tree

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#8]

**Comment by Harshalszz** [comment]
Hey! can I work on this.

**Comment by rodrigueseva** [comment]
added Optimal Binary Search Tree Using Dynamic Programming in c++
PR #12

**Comment by shin-iji** [comment]
@zahinekbal can i do this in python?

**Comment by ahmedashfaq027** [comment]
Hey, Can i do this in Java?

**Comment by saiharsha-22** [comment]
@zahinekbal can I do in java?

**Comment by zahinekbal** [comment]
> @zahinekbal can i do this in python?

yeah go ahead

**Comment by zahinekbal** [comment]
> @zahinekbal can I do in java?

yeah go ahead

**Comment by zahinekbal** [comment]
> @zahinekbal can I do in java?

Sorry @saiharsha-22 I think @ahmedashfaq027 is doing the same thing

**Comment by ahmedashfaq027** [comment]
#93 Added BinarySearchTree.java
