### ISSUE TITLE
Unique Number Using Bitwise Operator

### ISSUE THREAD

**Issue by zahinekbal** [zahinekbal/codeWith-hacktoberfest#97]
### Given a list of numbers where every Numbers occurs twice except one, find that Unique Number.....??
Ex:-3 , 2 ,3 , 5 , 6 , 5 , 2 :- OUTPUT :- 6

### File format :- BitWise/CPP/UniqueNumber.C++

Before making Pr
Please add your image in image folder nd update readme.md file it is all for contributors
do this then only i will be able to merge this..
Check this
#90 (comment)

**Comment by ahmedashfaq027** [comment]
I'm gonna add this in Java, Please assign!

**Comment by zahinekbal** [comment]
> I'm gonna add this in Java, Please assign!

Yes go ahead

**Comment by saipranay47** [comment]
can I go  ahead in java

**Comment by zahinekbal** [comment]
> can I go ahead in java

Sorry @saipranay47 It is based upon the priority who asked  first to assign the  issues will get it first ..
You can go with C++ or C....

**Comment by saipranay47** [comment]
ok @zahinekbal I will go ahead with c++ can u please suggest me how to start 
I mean where to add the file I am new to Github

**Comment by zahinekbal** [comment]
> ok @zahinekbal I will go ahead with c++ can u please suggest me how to start
> I mean where to add the file I am new to Github

Make a folder of UniqueNumberBitwise 
Then inside it made folder of C++ then inside it
Create file UniqueNumberBitwise .C++

Mns 
### UniqueNumberBitwise/C++/UniqueNumberBitwise .c++

**Comment by zahinekbal** [comment]
I already mentioned in the description box how to mention the file check it ....
Before making pr

**Comment by harshita-sharma11** [comment]
Can I do this in c++?

**Comment by saipranay47** [comment]
whin I try to clone it is giving this message @zahinekbal an ERROR 
----------------------------------
$ git clone https://github.com/saipranay47/codeWith-hacktoberfest.git
Cloning into 'codeWith-hacktoberfest'...
remote: Enumerating objects: 770, done.
remote: Total 770 (delta 0), reused 0 (delta 0), pack-reused 770
Receiving objects: 100% (770/770), 998.74 KiB | 29.00 KiB/s, done.
Resolving deltas: 100% (225/225), done.
error: invalid path 'Standard Questions/Algebra/Number-theoretic functions/Euler's totient function/SPOJ #4141 "Euler Totient Function" [Difficulty: CakeWalk].cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
--------------------------

**Comment by zahinekbal** [comment]
> ## whin I try to clone it is giving this message @zahinekbal an ERROR
> ## $ git clone https://github.com/saipranay47/codeWith-hacktoberfest.git
> Cloning into 'codeWith-hacktoberfest'...
> remote: Enumerating objects: 770, done.
> remote: Total 770 (delta 0), reused 0 (delta 0), pack-reused 770
> Receiving objects: 100% (770/770), 998.74 KiB | 29.00 KiB/s, done.
> Resolving deltas: 100% (225/225), done.
> error: invalid path 'Standard Questions/Algebra/Number-theoretic functions/Euler's totient function/SPOJ #4141 "Euler Totient Function" [Difficulty: CakeWalk].cpp'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

Hey I just fixed the errors yesterday also so now you hv to update your fork ..
Mns just delete the repo now then again fork it nd clone it ..
It will definitely work for you...

**Comment by saipranay47** [comment]
it's working thank you
 @zahinekbal

**Comment by saipranay47** [comment]
hey, 
I am down please merge my pr #114 
and add hacktober - accepted
